### PR TITLE
Documentation for 'signatory_role' and the 'approve' call

### PR DESCRIPTION
**Pull request by 23Skidoo**
[CORE-187](https://scriveab.atlassian.net/browse/CORE-187).

---
This change is [Reviewable](https://reviewable.io/reviews/scrive/scrive-apidocs/39)

### CODE REVIEW

**Comment by jonathanjouty** [comment]
Problems found with examples. Otherwise looks good.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[documentation/scrive_api.yaml, line 60 at r1](https://reviewable.io/reviews/scrive/scrive-apidocs/39#-LC2rDER2zfP9lDRr5Kk:-LC2rDER2zfP9lDRr5Kl:b-poivin) ([raw file](https://github.com/scrive/scrive-apidocs/blob/a9c7b693641f74aee9f8c3c896f61bb68f0672d3/documentation/scrive_api.yaml#L60)):*
> ```YAML
>     |             | Factor out `SignatoryFieldStandard` into `SignatoryFieldEmailMobile` to allow for `editable_by_signatory` property |
>     | 2017-11-15  | Custom validations for the `SignatoryFieldCustomField` are now supported |
>     | 2018-05-XX  | New `Signatory` field `signatory_role`, supercedes `is_signatory`. |
> ```

Date will need to be updated before merge.

---

*[documentation/api/documents/document_id/signatory_id/reject.yaml, line 13 at r1](https://reviewable.io/reviews/scrive/scrive-apidocs/39#-LC2s7zA9DDUeh2WOYsM:-LC2s7zA9DDUeh2WOYsN:b-ubnl0o) ([raw file](https://github.com/scrive/scrive-apidocs/blob/3e4e1123e8148df3567973221caafa0a7ed51120/documentation/api/documents/document_id/signatory_id/reject.yaml#L13)):*
> ```YAML
>     Reject signing the document for the given signatory.
> 
>     If successfull, this will prevent any future signatories from signing and
> ```

Nice find :)

---

*[documentation/definitions/Document.yaml, line 225 at r1](https://reviewable.io/reviews/scrive/scrive-apidocs/39#-LC2tGq8-Tq39OKo27Mc:-LC2sYVe8i6anRl_FbIH:bbqu8b) ([raw file](https://github.com/scrive/scrive-apidocs/blob/a9c7b693641f74aee9f8c3c896f61bb68f0672d3/documentation/definitions/Document.yaml#L225)):*
> ```YAML
>         "user_id": "1404",
>         "is_author": true,
>         "signatory_role": "viewer",
> ```

In `Signatory.yaml` you are keeping `is_signatory` and adding `signatory_role`.
That seems correct, as it prevents breaking changes.
The change here is not in line with that.

---

*[documentation/definitions/Document.yaml, line 282 at r1](https://reviewable.io/reviews/scrive/scrive-apidocs/39#-LC2tbjgBIMrPsp2Di9G:-LC2tbjgBIMrPsp2Di9H:b2nreh6) ([raw file](https://github.com/scrive/scrive-apidocs/blob/a9c7b693641f74aee9f8c3c896f61bb68f0672d3/documentation/definitions/Document.yaml#L282)):*
> ```YAML
>         "user_id": null,
>         "is_author": false,
>         "signatory_role": "signing_party",
> ```

Same as above.

---

*[documentation/definitions/Signatory.yaml, line 31 at r1](https://reviewable.io/reviews/scrive/scrive-apidocs/39#-LC2thbV0bIhe0JBwKvd:-LC2thbV0bIhe0JBwKve:b2plz64) ([raw file](https://github.com/scrive/scrive-apidocs/blob/a9c7b693641f74aee9f8c3c896f61bb68f0672d3/documentation/definitions/Signatory.yaml#L31)):*
> ```YAML
>       Whether this party is a signatory to the document, otherwise
>       they are viewers and will not sign the document. This field is
>       optional: if a `signatory_role` field is present, the value of
> ```

Is it worth specifying that field is optional for updates?

---

*[documentation/definitions/Signatory.yaml, line 234 at r1](https://reviewable.io/reviews/scrive/scrive-apidocs/39#-LC2twPR9DVRYqyN5Vzy:-LC2twPR9DVRYqyN5Vzz:b-lhjx36) ([raw file](https://github.com/scrive/scrive-apidocs/blob/a9c7b693641f74aee9f8c3c896f61bb68f0672d3/documentation/definitions/Signatory.yaml#L234)):*
> ```YAML
>     "user_id": null,
>     "is_author": false,
>     "signatory_role": "signing_party",
> ```

Same as with other examples, you removed `is_signatory`

---


*Comments from [Reviewable](https://reviewable.io/reviews/scrive/scrive-apidocs/39#-:-LC2u6MCAlx1y-pviLb3:bsv74h5)*

**Comment by 23Skidoo** [comment]
Review status: 4 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[documentation/definitions/Document.yaml, line 225 at r1](https://reviewable.io/reviews/scrive/scrive-apidocs/39#-LC2tGq8-Tq39OKo27Mc:-LC3Tm-nE-wpou0BFqZ0:b-ox6gzv) ([raw file](https://github.com/scrive/scrive-apidocs/blob/a9c7b693641f74aee9f8c3c896f61bb68f0672d3/documentation/definitions/Document.yaml#L225)):*
<details><summary><i>Previously, jonathanjouty (Jonathan Jouty) wrote…</i></summary><blockquote>

In `Signatory.yaml` you are keeping `is_signatory` and adding `signatory_role`.
That seems correct, as it prevents breaking changes.
The change here is not in line with that.
</blockquote></details>

OK, fixed the examples.

---

*[documentation/definitions/Document.yaml, line 282 at r1](https://reviewable.io/reviews/scrive/scrive-apidocs/39#-LC2tbjgBIMrPsp2Di9G:-LC3U7OrBqe-WfNOUuI5:b-896fix) ([raw file](https://github.com/scrive/scrive-apidocs/blob/a9c7b693641f74aee9f8c3c896f61bb68f0672d3/documentation/definitions/Document.yaml#L282)):*
<details><summary><i>Previously, jonathanjouty (Jonathan Jouty) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

---

*[documentation/definitions/Signatory.yaml, line 31 at r1](https://reviewable.io/reviews/scrive/scrive-apidocs/39#-LC2thbV0bIhe0JBwKvd:-LC3UKQS5FZWSeAL_XLM:bkbl3hn) ([raw file](https://github.com/scrive/scrive-apidocs/blob/a9c7b693641f74aee9f8c3c896f61bb68f0672d3/documentation/definitions/Signatory.yaml#L31)):*
<details><summary><i>Previously, jonathanjouty (Jonathan Jouty) wrote…</i></summary><blockquote>

Is it worth specifying that field is optional for updates?
</blockquote></details>

You want this sentence to be clarified?

---

*[documentation/definitions/Signatory.yaml, line 234 at r1](https://reviewable.io/reviews/scrive/scrive-apidocs/39#-LC2twPR9DVRYqyN5Vzy:-LC3UOaA-In-xyH54JtB:b-896fix) ([raw file](https://github.com/scrive/scrive-apidocs/blob/a9c7b693641f74aee9f8c3c896f61bb68f0672d3/documentation/definitions/Signatory.yaml#L234)):*
<details><summary><i>Previously, jonathanjouty (Jonathan Jouty) wrote…</i></summary><blockquote>

Same as with other examples, you removed `is_signatory`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scrive/scrive-apidocs/39)*

**Comment by jonathanjouty** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[documentation/definitions/Signatory.yaml, line 31 at r1](https://reviewable.io/reviews/scrive/scrive-apidocs/39#-LC2thbV0bIhe0JBwKvd:-LC400Sg8s_o0F3oWomL:b1n3ac9) ([raw file](https://github.com/scrive/scrive-apidocs/blob/a9c7b693641f74aee9f8c3c896f61bb68f0672d3/documentation/definitions/Signatory.yaml#L31)):*
Maybe, yes!
Something like:
> This field is optional when updating a document: if a `signatory_role` is...

---


*Comments from [Reviewable](https://reviewable.io/reviews/scrive/scrive-apidocs/39)*

**Comment by 23Skidoo** [comment]
Reviewed 4 of 6 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[documentation/scrive_api.yaml, line 60 at r1](https://reviewable.io/reviews/scrive/scrive-apidocs/39#-LC2rDER2zfP9lDRr5Kk:-LC4F4AU8G7WKMoNjLZV:b32w0x) ([raw file](https://github.com/scrive/scrive-apidocs/blob/a9c7b693641f74aee9f8c3c896f61bb68f0672d3/documentation/scrive_api.yaml#L60)):*
<details><summary><i>Previously, jonathanjouty (Jonathan Jouty) wrote…</i></summary><blockquote>

Date will need to be updated before merge.
</blockquote></details>

OK

---

*[documentation/definitions/Signatory.yaml, line 31 at r1](https://reviewable.io/reviews/scrive/scrive-apidocs/39#-LC2thbV0bIhe0JBwKvd:-LC4EmTAEl0ZBj3Es0q4:b-896fix) ([raw file](https://github.com/scrive/scrive-apidocs/blob/a9c7b693641f74aee9f8c3c896f61bb68f0672d3/documentation/definitions/Signatory.yaml#L31)):*
<details><summary><i>Previously, jonathanjouty (Jonathan Jouty) wrote…</i></summary><blockquote>

Maybe, yes!
Something like:
> This field is optional when updating a document: if a `signatory_role` is...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scrive/scrive-apidocs/39)*

**Comment by jonathanjouty** [comment]
All good!

We just need to fix the release date once we know it.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/scrive/scrive-apidocs/39#-:-LCSf7437wUYBH7wXxEw:b5u0o77)*

**Comment by jonathanjouty** [comment]
@23Skidoo could you fix conflicts and release date?

**Comment by 23Skidoo** [comment]
Sure, but what will be the release date?

**Comment by jonathanjouty** [comment]
I believe Monday 17th December.
You can confirm with @trin-cz tomorrow.

**Comment by 23Skidoo** [comment]
Rebased and updated to reflect the latest changes.

**Pull request merged**
