### PR TITLE
CORE-1338 - add sms_pin to ATV and ATVA documentation

### PR DESCRIPTION
**Pull request by trin-cz**
https://scriveab.atlassian.net/browse/CORE-1338

This change is [Reviewable](https://reviewable.io/reviews/scrive/scrive-apidocs/52)

### CODE REVIEW

**Comment by wwwater** [comment]
@trin-cz seems that I'm not authorized to merge, so you need to merge yourself

**Comment by jonathanjouty** [comment]
@wwwater It seems to be because "This branch is out-of-date with the base branch"
Updating branch and then we should be able to do it after CI build passes.

**Comment by jonathanjouty** [comment]
It's happy now :)
Merging.

**Comment by wwwater** [comment]
@jonathanjouty I explicitly get `The base branch restricts merging to authorized users.`

**Pull request merged**
