### PR TITLE
Document Radio button fields: radiogroup

### PR DESCRIPTION
**Pull request by jonathanjouty**
Case 3271.

@trin-cz no rush, when you're back from holidays you can have a look ;)

### CODE REVIEW

**Comment by jonathanjouty** [comment]
Also:
# DO NOT MERGE YET :(

**Comment by trin-cz** [comment]
We should list radio button sizes in api docs, because we do not accept any other sizes. See RadiobuttonPlacementUtils.

**Comment by trin-cz** [comment]
I don't understand the note about missing common SignatoryField properties.

**Comment by trin-cz** [comment]
The length of `values` MUST match that of `placements`, because if not, an error is returned.

**Comment by mariuszrak** [comment]
Sorry but I will have to reject that.
Descriptions of all other fields is based on extending of SignatoryField definition, and we should do the same for radio buttons. Only problem with that is having to redefine `is_obligatory` in all field types - because it will start being common part.

On top of that It would be nice to specify allowed sizes of checkboxes and radiobuttons. We only allow certain wres, frel and so on. Some of them need to be 0, and some need to have a fixed values.

**Comment by jonathanjouty** [comment]
Thanks for feedback @trin-cz, will fix.

Talked with @mariuszrak too, and I will refactor the whole way signatory fields documentation is organised.

**Comment by jonathanjouty** [comment]
Closing in favour of #18.

**Pull request closed without merging**
