### PR TITLE
FLOW-283 Allow filtering flow docs in list calls

### PR DESCRIPTION
**Pull request by tombusby**
This change is [Reviewable](https://reviewable.io/reviews/scrive/scrive-apidocs/102)

### CODE REVIEW

**Review by Siprj — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scrive/scrive-apidocs/102)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mbernat and @tombusby)

___
*[documentation/definitions/ListFilter.yaml, line 6 at r1](https://reviewable.io/reviews/scrive/scrive-apidocs/102#-MKiP2yMDH3zrZv5w5Iy:-MKiP2yN5aQ3SBQ2Cs0f:b-n3mkim) ([raw file](https://github.com/scrive/scrive-apidocs/blob/4d678a24a34b479a923546a9d96a7c604714d25a/documentation/definitions/ListFilter.yaml#L6)):*
> ```YAML
> description: Parameter used to filter documents for the `list` API call.
> type: array
> default: []
> ```

If I read the code correctly we changed the default.

**Review by tombusby — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scrive/scrive-apidocs/102)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mbernat and @Siprj)

___
*[documentation/definitions/ListFilter.yaml, line 6 at r1](https://reviewable.io/reviews/scrive/scrive-apidocs/102#-MKiP2yMDH3zrZv5w5Iy:-MKiRf-_E0l2EwreRtnD:bvioh19) ([raw file](https://github.com/scrive/scrive-apidocs/blob/4d678a24a34b479a923546a9d96a7c604714d25a/documentation/definitions/ListFilter.yaml#L6)):*
<details><summary><i>Previously, Siprj (Jan Šipr) wrote…</i></summary><blockquote>

If I read the code correctly we changed the default.
</blockquote></details>

No, the list call by default doesn't apply any filters, we apply the filter when calling the list call from old frontend.

**Review by Siprj — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scrive/scrive-apidocs/102)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mbernat)

**Comment by tombusby** [comment]
@Siprj cool cheers, I'll set a reminder to merge this when this goes to prod.

**Pull request merged**
