### PR TITLE
Add /signup endpoint from dev-user-api branch

### PR DESCRIPTION
**Pull request by wwwater**
Also take better description for loginandgetsession endpoint from that
branch

---
This change is [Reviewable](https://reviewable.io/reviews/scrive/scrive-apidocs/49)

### CODE REVIEW

**Comment by tageborg** [comment]
Is this stuck for some particular reason? @jonathanjouty

**Comment by jonathanjouty** [comment]
It's just stuck on me not having reviewed it yet.
Will prioritise.

**Comment by jonathanjouty** [comment]
I've done a few things in 380fe8374660227e0f3129c176e839f96e1f4a8f:
1. Improve the descriptions further, they were not 100% clear in retrospect
2. Remove the error responses, we don't have them for most endpoints, and it makes the documentation look noisy

Other are more minor:
1. Add `type: string` to `personal_token` parameter
2. Clarify wording in `signup` parameters and response a bit

@wwwater could you have a look to make sure I didn't do anything silly?
I'll mark review as _Approved_ so it should be OK to merge.

**Comment by wwwater** [comment]
@jonathanjouty I still miss right to approve and merge PRs in this repo. I fixed a typo, so you can merge it now.

**Comment by jonathanjouty** [comment]
Hmm, I thought you should be able to merge if all checks pass :/
Not sure why you cannot...

Thanks for the typo fix.
Merging.

**Comment by jonathanjouty** [comment]
Only took three months 😢 
Sorry about that! 😊

**Pull request merged**
