### PR TITLE
CORE-1840 user tags api

### PR DESCRIPTION
**Pull request by mbernat**
This change is [Reviewable](https://reviewable.io/reviews/scrive/scrive-apidocs/83)

### CODE REVIEW

**Comment by trin-cz** [comment]
I will merge this once the code is in production.

**Comment by mbernat** [comment]
@trin-cz seems we forgot to merge this :)

**Comment by jonathanjouty** [comment]
@mbernat is the branch that this got merged to meant to be merged to `master`?
Because right now it doesn't appear to be?

**Comment by mbernat** [comment]
@jonathanjouty Oh, well spotted, I have no idea what state is any of this in, have to investigate. Thanks!

**Comment by mbernat** [comment]
Yeah, this is all wrong, it should've been merged into master. I have to create a new PR and do it properly.

**Pull request merged**
